### ISSUE TITLE
Terminated when using 01_parse.py

### ISSUE THREAD

**Issue by santoshbs** [explosion/sense2vec#109]
I am trying to pre-train on wiki corpus. I have created a single wiki dump file with one sentence per line. Everytime I run the 01_parse.oy I get "Terminated" as status after running for hours. 

`Preprocessing text...
Docs: 26327466 [4:49:48, 1372.34/s]Terminated
`
Not sure what is the issue.

**Comment by honnibal** [comment]
Is it possible you're running out of memory? How big is the file?

**Comment by santoshbs** [comment]
The wiki dump file is 12 gb. Not sure if and how I can split and use the 01_parse.py.

Many thanks!

**Comment by santoshbs** [comment]
Using the recent fix that splits the dump file into 10**6 docs per iteration helped.

**Comment by svlandeg** [comment]
Ah, glad to hear it @santoshbs, thanks for reporting back !
So if PR #103 fixed this for you, I guess we can close this issue?
