### ISSUE TITLE
cosine similarity: import error

### ISSUE THREAD

**Issue by santoshbs** [explosion/sense2vec#110]
When am trying to use the `05_export.py` from the Scripts folder and I get the following error: 
`ImportError: cannot import name 'cosine_similarity' from 'sense2vec.util' 
`
When I try to install the github version of sense2vec, I get the following error:
`error: srsly 2.0.1 is installed but srsly<1.1.0,>=1.0.2 is required by {'spacy'}
`
May I request your kind help with this?

Thanks!

**Comment by santoshbs** [comment]
I fixed this issue for now. Instead of using the pip version of sense2vec, I downloaded the current git version. A separate Python virtual environment helped resolve the srsly and other packages issue. I made the necessary changes to files in the Scripts folder to point to the relevant packages. I was able to finally get the Wikipedia-trained contextually-cued word vectors!

**Comment by svlandeg** [comment]
Thanks for posting the work-around, and happy to hear it now works for you!

**Comment by UrbanListings** [comment]
On GitHub, resolution approach is not defined as appropriately on Other sites. Plus closing the issue must be marked with well documentation of solution.
