### ISSUE TITLE
Error while using merge_text.py

### ISSUE THREAD

**Issue by zikaadam** [explosion/sense2vec#12]
Hi,

I am getting the following error while pre-processing data with merge_text.py:

```
Traceback (most recent call last):
  File "C:/Users/Adam/Google Drive/TUe/3 Semester/_thesis/Pycharm/LeadUserIdentification/sense2vec/bin/merge_text.py", line 143, in <module>
    main('a','b', n_workers=1)
  File "C:/Users/Adam/Google Drive/TUe/3 Semester/_thesis/Pycharm/LeadUserIdentification/sense2vec/bin/merge_text.py", line 139, in main
    parallelize(do_work, enumerate(jobs), n_workers, [out_dir])
  File "C:/Users/Adam/Google Drive/TUe/3 Semester/_thesis/Pycharm/LeadUserIdentification/sense2vec/bin/merge_text.py", line 48, in parallelize
    return Parallel(n_jobs=n_jobs)(delayed(func)(*(item + extra)) for item in iterator)
  File "C:\Users\Adam\Anaconda2\lib\site-packages\joblib\parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\Adam\Anaconda2\lib\site-packages\joblib\parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Adam\Anaconda2\lib\site-packages\joblib\parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "C:\Users\Adam\Anaconda2\lib\site-packages\joblib\parallel.py", line 180, in __init__
    self.results = batch()
  File "C:\Users\Adam\Anaconda2\lib\site-packages\joblib\parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "C:/Users/Adam/Google Drive/TUe/3 Semester/_thesis/Pycharm/LeadUserIdentification/sense2vec/bin/merge_text.py", line 92, in parse_and_transform
    file_.write(transform_doc(nlp(strip_meta(text))))
  File "C:/Users/Adam/Google Drive/TUe/3 Semester/_thesis/Pycharm/LeadUserIdentification/sense2vec/bin/merge_text.py", line 98, in transform_doc
    for np in doc.noun_chunks:
  File "spacy/tokens/doc.pyx", line 246, in noun_chunks (spacy/tokens/doc.cpp:7745)
    for start, end, label in self.noun_chunks_iterator(self):
  File "spacy/syntax/iterators.pyx", line 11, in english_noun_chunks (spacy/syntax/iterators.cpp:1559)
    word = doc[i]
  File "spacy/tokens/doc.pyx", line 100, in spacy.tokens.doc.Doc.__getitem__ (spacy/tokens/doc.cpp:4853)
    if self._py_tokens[i] is not None:
IndexError: list index out of range
```

I run the _merge_text.py_ with `n_workers=1`. Btw. I did a minor change of function `iter_comments` to work with plain text input:

```
def iter_comments(loc):
    with open(loc) as file_:
        for i, line in enumerate(file_):
            yield line
```

Do you have an idea why this happen?

Thank you,
Adam

**Comment by elyase** [comment]
Something similar happened to me. I think the reason was empty documents or docs with only punctuation. In this line:
```
file_.write(transform_doc(nlp(strip_meta(text))))
```

make sure that you don't have empty or otherwise weird documents, something like:

```
text =  strip_meta(text)
if len(text) > 40: 
    file_.write(transform_doc(nlp(text)))
```

**Comment by zikaadam** [comment]
@elyase, thanks for the quick reply! I checked the file and it does not have any empty lines or punctuation lines only. Also tried to apply `if len(text) > 40:`, but it did not help.

`transform_doc `function actually crushed with this input _"how do i get my home screen to rotate on the iphone 6 plea"_. I work with tweets, so the messages are quite empty.

**Comment by elyase** [comment]
You are right, this is also broken for me now. It looks like something broke np.merge in the last versions. May be try installing an older (two or three versions back) spacy?

I reported the bug [here](https://github.com/spacy-io/spaCy/issues/375).

**Comment by zikaadam** [comment]
Thanks @elyase. I tried older versions, but without any success. Actually, i wasn't able to install them. Always got an error. I will look around for some other sense2vec implementations.

**Comment by elyase** [comment]
Did you try the workaround [here](https://github.com/spacy-io/spaCy/issues/375)? It should work with current spacy version.

**Comment by AnjanaRita** [comment]
the code in this file merge_text.py use an older version of spacy. That is the reason for getting an error.So, i change in that file and the code is running perfectly.

`from __future__ import print_function, unicode_literals, division
import io
import bz2
import logging
from toolz import partition
from os import path
import os
import re

import spacy
from preshed.counter import PreshCounter
from spacy.tokens.doc import Doc

from joblib import Parallel, delayed
import plac
try:
    import ujson as json
except ImportError:
    import json


LABELS = {
    'ENT': 'ENT',
    'PERSON': 'ENT',
    'NORP': 'ENT',
    'FAC': 'ENT',
    'ORG': 'ENT',
    'GPE': 'ENT',
    'LOC': 'ENT',
    'LAW': 'ENT',
    'PRODUCT': 'ENT',
    'EVENT': 'ENT',
    'WORK_OF_ART': 'ENT',
    'LANGUAGE': 'ENT',
    'DATE': 'DATE',
    'TIME': 'TIME',
    'PERCENT': 'PERCENT',
    'MONEY': 'MONEY',
    'QUANTITY': 'QUANTITY',
    'ORDINAL': 'ORDINAL',
    'CARDINAL': 'CARDINAL'
}


def parallelize(func, iterator, n_jobs, extra):
    extra = tuple(extra)
    return Parallel(n_jobs=n_jobs)(delayed(func)(*(item + extra)) for item in iterator)


def iter_comments(loc):
    with bz2.BZ2File(loc) as file_:
        for i, line in enumerate(file_):
            yield ujson.loads(line)['body']


pre_format_re = re.compile(r'^[\`\*\~]')
post_format_re = re.compile(r'[\`\*\~]$')
url_re = re.compile(r'\[([^]]+)\]\(%%URL\)')
link_re = re.compile(r'\[([^]]+)\]\(https?://[^\)]+\)')
def strip_meta(text):
    text = link_re.sub(r'\1', text)
    text = text.replace('&gt;', '>').replace('&lt;', '<')
    text = pre_format_re.sub('', text)
    text = post_format_re.sub('', text)
    return text


def load_and_transform(batch_id, in_loc, out_dir):
    out_loc = path.join(out_dir, '%d.txt' % batch_id)
    if path.exists(out_loc):
        return None
    print('Batch', batch_id)
    nlp = spacy.load("en")
    #nlp = spacy.en.English(parser=False, tagger=False, matcher=False, entity=False)
    with io.open(out_loc, 'w', encoding='utf8') as out_file:
        with io.open(in_loc, 'rb') as in_file:
            for byte_string in Doc.read_bytes(in_file):
                doc = Doc(nlp.vocab).from_bytes(byte_string)
                doc.is_parsed = True
                out_file.write(transform_doc(doc)) 


def parse_and_transform(batch_id, input_, out_dir):
    out_loc = path.join(out_dir, '%d.txt' % batch_id)
    if path.exists(out_loc):
        return None
    print('Batch', batch_id)
    nlp = spacy.load("en")
    nlp.matcher = None
    with io.open(out_loc, 'w', encoding='utf8') as file_:
        for text in input_:
            file_.write(transform_doc(nlp(strip_meta(text))))


def transform_doc(doc):
    for ent in doc.ents:
        ent.merge(ent.root.tag_, ent.text, LABELS[ent.label_])
    for np in doc.noun_chunks:
        while len(np) > 1 and np[0].dep_ not in ('advmod', 'amod', 'compound'):
            np = np[1:]
        np.merge(tag = np.root.tag_, lemma= np.text, ent_type =np.root.ent_type_)
    strings = []
    for sent in doc.sents:
        if sent.text.strip():
            strings.append(' '.join(represent_word(w) for w in sent if not w.is_space))
    if strings:
        return '\n'.join(strings) + '\n'
    else:
        return ''


def represent_word(word):
    if word.like_url:
        return '%%URL|X'
    text = re.sub(r'\s', '_', word.text)
    #print word.ent_type_
    tag = LABELS.get(word.ent_type_, word.pos_)
    if not tag:
        tag = '?'
    return text + '|' + tag


@plac.annotations(
    in_loc=("Location of input file"),
    out_dir=("Location of input file"),
    n_workers=("Number of workers", "option", "n", int),
    load_parses=("Load parses from binary", "flag", "b"),
)
def main(in_loc, out_dir, n_workers=4, load_parses=False):
    if not path.exists(out_dir):
        path.join(out_dir)
    if load_parses:
        jobs = [path.join(in_loc, fn) for fn in os.listdir(in_loc)]
        do_work = load_and_transform
    else:
        jobs = partition(200000, iter_comments(in_loc))
        do_work = parse_and_transform
    parallelize(do_work, enumerate(jobs), n_workers, [out_dir])
 

if __name__ == '__main__':
    plac.call(main)`

**Comment by AnjanaRita** [comment]
The code in merge_file.py use an older version of spacy.so I make some changes in a file and it is working perfectly.try this. 
[merge_file.txt](https://github.com/explosion/sense2vec/files/1791891/merge_file.txt)
