### ISSUE TITLE
Segmentation Fault with sense2vec loading

### ISSUE THREAD

**Issue by sevaader** [explosion/sense2vec#13]
I successfully installed sense2vec with python2.7 on Ubuntu.
I installed python -m sense2vec.download
I successully loaded the model multiples times with the following code:

```
>>import sense2vec
>>model = sense2vec.load()
>>
```

but, now the sense2vec load creates _Segmentation Fault (code dumped)_

```
>>import sense2vec
>>model = sense2vec.load()
Segmentation Fault
```

I force download the model again with download.py --force, and I'm still locked with _Segmentation Fault._. Any idea to slove it ?

**Comment by pdeburen** [comment]
The model needs quite a lot of memory, how much RAM do you have?
