### ISSUE TITLE
No Build for m1 Mac

### ISSUE THREAD

**Issue by ahmedjamshed** [explosion/sense2vec#145]
Is it possible to install it on m1 Mac directly, without using rosetta? Tried miniforge with no luck!

**Comment by adrianeboyd** [comment]
Do you mean installing spacy and its dependencies? `spacy` should be provided from conda-forge through miniforge (`conda install -c conda-forge spacy`), but you'd need to install `sense2vec` with pip. It's a python-only package, so it doesn't have platform-dependent wheels or packages.

Without more specific error messages it's hard to know where the problem might be...

**Comment by ahmedjamshed** [comment]
I found a solution, so I think it's working fine now. Thanks!
