### ISSUE TITLE
[Question] Why not Word2Vec?

### ISSUE THREAD

**Issue by santoshbs** [explosion/sense2vec#154]
I was curious to know why only glove and fasttext are provided as options for training, and not word2vec (e.g., genism). 

Relatedly, are there any accuracy benchmarks for sense2vec with training using three different approaches: glove, word2vec, vs. fasttext?  

Thanks!
S

**Comment by adrianeboyd** [comment]
As far as I know, these were just two commonly-used alternatives at the time and there's no reason you couldn't write a similar script for step 4 for gensim/word2vec.

This [blog post](https://explosion.ai/blog/sense2vec-reloaded) describes a few comparisons that were made related to the vector training for the models retrained in 2019:

> We also ran evaluations to decide the choice of algorithm (skipgram with negative samples vs GloVe, preferring the skipgrams output), the window size (5 vs. 15, preferring the narrower window), and character vs word features (choosing to disable FastText’s character ngrams).
