### ISSUE TITLE
Support for Non-English languages

### ISSUE THREAD

**Issue by narudarurarasya** [explosion/sense2vec#16]
Google's Syntaxnet has released pre-trained models for 40 other languages. 

May I know if any of these can be used (with Spacy's Sense2Vec) to train word embeddings in languages other than English?

Thanks

**Comment by elyase** [comment]
To my knowledge neither spacy, sense2vec nor Google McParsey can train word embeddings. You mean using the POS tags from syntaxnet instead of spacy's?

**Comment by vaddina** [comment]
yes, to load POS Tags... 😊  Spacy states that it only currently supports English & German. (please correct if wrong)
So I was wondering if it's possible to leverage Syntaxnet capabilities to get POS tags in 40 other languages. (And then train sense2vec on them)

**Comment by elyase** [comment]
I don't see why not. First rewrite the corresponding version of `bin/merge_text.py` to use Syntaxnet instead of spacy (for example using [this](https://github.com/plowman/python-mcparseface), then the rest should remain the same.

**Comment by vaddina** [comment]
Cool.. I shall take a look. Thanks 👍

**Comment by alagaro** [comment]
Greetings!, I am currently doing an investigation on text simplification in Spanish language, did you managed to train sense2vec on this language? if so please tell me how, or if u have the model, that would help me a lot
