### ISSUE TITLE
How to calculate the similarity between two words

### ISSUE THREAD

**Issue by yixiongsun** [explosion/sense2vec#24]
Installed the sense2vec successfully and run model.most_similar(query_vector) without any problem, i.e., I can get most similar words. 

However, trying to run the example of similarity score of two words, model.similarity('bacon|NOUN', 'broccoli|NOUN'), it yields the error message: 
AttributeError: 'sense2vec.vectors.VectorMap' object has no attribute 'similarity'.

So, what's the right method to calculate the score of two words? Thanks!

**Comment by honnibal** [comment]
`model.data.similarity(vector1, vector2)`

(Not wonderful, I know...)

**Comment by yixiongsun** [comment]
It works. Thank you, honnibal!

**Comment by yixiongsun** [comment]
Hi, Honnibal, 
Based on the sense2vec, how do you think about the best algorithm to compute the similarity of two sentences? Much appreciation!

**Comment by honnibal** [comment]
@yixiongsun That's a deep topic -- it depends on what definition of similarity you want. I wrote some blog posts with preliminary work, but don't have a really good go-to solution at the moment. https://explosion.ai/blog/supervised-similarity-siamese-cnn
