### ISSUE TITLE
sense2vec drags spacy to older version?

### ISSUE THREAD

**Issue by jjasonbell** [explosion/sense2vec#25]
I'm wanting to use the reddit vectors for analogies.  When I install sense2vec, I run into the old issue that lexemes are unhashable.  I saw that this was fixed in September of 2016, so I updated spacy, but then sense2vec complains:

    spacy.strings.StringStore has the wrong size, try recompiling
Recompiling leads to unhashable lexemes again...

Am I right that the sense2vec installation uses an earlier version of spacy, or am I just clueless?  Any ideas for a workaround?

**Comment by tc64** [comment]
in requirements-all.txt there is this line:
spacy>=0.100,<0.101

I think this means if you install with pip, your spacy version will revert when installing dependencies.

**Comment by parasurama** [comment]
If i revert back to spacy 0.101.0, it throws this error when loading spacy models

`line 15, in __init__
    super(Package, self).__init__(defaults=meta['package'])
KeyError: 'package'
`

**Comment by honnibal** [comment]
Fixed now :)
