### ISSUE TITLE
Segmentation fault with merge_text.py

### ISSUE THREAD

**Issue by Jack000** [explosion/sense2vec#26]
Trying to train sense2vec on wikipedia.

after python -m spacy.en.download
when running sense2vec/bin/merge_text.py -b ~/input_dir ~/output_dir

where input_dir is a directory of cleaned wikipedia articles in plaintext files.

I get a segmentation fault in the worker threads, and 4 empty text files in output_dir

any ideas? Would it be possible to get a pre-trained, non-reddit model?

**Comment by honnibal** [comment]
Sorry for leaving this unmaintained so long, and thanks for your help. @ines has just pushed a big update getting it in line with spaCy 2. We'll be adding updated scripts soon.
