### ISSUE TITLE
Incompatible spaCy model when using sense2vec

### ISSUE THREAD

**Issue by parasurama** [explosion/sense2vec#28]
Installing sense2vec rolls back spacy version to 0.101.0 as documented here: https://github.com/explosion/sense2vec/issues/25

However, none of the current english spaCy models are [compatible](https://github.com/explosion/spacy-models/releases) with 0.101.0  and raises this error when trying to load:

`    super(Package, self).__init__(defaults=meta['package'])
KeyError: 'package'
`

Is there a way to download old spacy models? I mainly want to use spacy to get entity tagging (NOUN, GPE etc), which can then be passed to space2vec. 

Thank you!

**Comment by mike-a-yen** [comment]
Having the same issue here.

**Comment by honnibal** [comment]
Fixed now :)
