### ISSUE TITLE
NameError: global name 'ujson' is not defined

### ISSUE THREAD

**Issue by Dennett** [explosion/sense2vec#32]
in https://github.com/explosion/sense2vec/blob/master/bin/merge_text.py you import ujson as json:
```
try:
    import ujson as json
except ImportError:
    import json
```

but then call ujson as ujson, not json:

```
def iter_comments(loc):
    with bz2.BZ2File(loc) as file_:
        for i, line in enumerate(file_):
            yield ujson.loads(line)['body']
```

**Comment by honnibal** [comment]
Sorry for leaving this unmaintained so long, and thanks for your help. @ines has just pushed a big update getting it in line with spaCy 2. We'll be adding updated scripts soon.
