### ISSUE TITLE
sense2vec (0.6.0) not loading after upgrading spacy to version 1.8.2

### ISSUE THREAD

**Issue by surajitsen** [explosion/sense2vec#34]
sense2vec (0.6.0) is not working with latest spacy version 1.8.2.

I’m running Python (2.7.13) Anaconda version (4.3.22) on Ubuntu 14.04.4 LTS

It was working fine with spacy version 0.101.0, but after upgrading spacy and its corresponding model I’m unable to load sense2vec. Its throwing ValueError: spacy.strings.StringStore has the wrong size 

If I try to reinstall sense2vector, the spacy version getting reverted back to 0.101.0. 

We need to upgrade spacy to latest version for German and Spanish language support, and also need to continue using sense2vector in one of our existing  functionality.

Any idea how to resolve the current issue and have spacy (1.8.2) + textacy (0.3.4) + sense2vec (0.6.0) together on my system?

Here is spacy information installed on my system:
![image](https://user-images.githubusercontent.com/16769227/28210882-63d45514-68b7-11e7-857a-3e0e2adddf35.png)

![image](https://user-images.githubusercontent.com/16769227/28211094-77ea8cf2-68b8-11e7-9a5b-61a078f195f2.png)

And here is the error I’m getting when trying to import sense2vec:
![image](https://user-images.githubusercontent.com/16769227/28211108-8a86b2c8-68b8-11e7-85ce-48819e27dabb.png)

**Comment by clearnote01** [comment]
I have similar problem except I am using Spacy 2.02.

**Comment by exepaul** [comment]
@clearnote01 have you found any solution? i am also facing same issue.

**Comment by mikkokotila** [comment]
Also facing this same issue.

**Comment by felixheck** [comment]
Same here. Unable to use sense2vec with the current version of spacy.

@honnibal @ines – any comments?

**Comment by honnibal** [comment]
Should be fixed now :)
