### ISSUE TITLE
Train Sense2Vec on another dataset

### ISSUE THREAD

**Issue by aremirata** [explosion/sense2vec#36]
I am new to sense2vec. Is there a way we can train another dataset using sense2vec instead of using reddit? How can we do that?

**Comment by luisfredgs** [comment]
i'm very interested in this question too. Is there a way we can train sense2vec in my own dataset? How would be?

**Comment by nithinshiriya** [comment]
Hi There,  I am working on Legal document corpus database. I would like to train the dataset. Could you please let us know how to achieve this?.  @luisfredgs

**Comment by voxlogic** [comment]
I'd be very interested in learning more about the training process too. Been looking to train sense2vec on our custom text corpus as well.

**Comment by elyase** [comment]
There were some scripts in oldest sense2vec versions that would allow you to train a custom model in your dataset. See for example the `bin` folder here:

https://github.com/explosion/sense2vec/tree/e3e871d46101dfe51b2eff0f9ac4a6e15f951ef7

For this new sense2vec version @ines still hasn't uploaded the updated training scripts but I seem to remember that she mentioned they will be coming soon.

**Comment by tolomaus** [comment]
Indeed, building a custom sense2vec model is not all that complicated, see here a summary of how to do it, based on the scripts found in the previous version:

```
    w2v_model = Word2Vec(
        size=size,
        window=window,
        min_count=min_count,
        workers=workers,
        sample=1e-5,
        negative=negative,
        iter=epochs
    )

    sentences = PathLineSentences(path)

    print("building the vocabulary...")
    w2v_model.build_vocab(sentences)

    print("training the model...")
    w2v_model.train(sentences, total_examples=w2v_model.corpus_count, epochs=w2v_model.iter)

    print("creating the sense2vec model...")
    vector_map = VectorMap(size)

    for string in w2v_model.wv.vocab:
        vocab = w2v_model.wv.vocab[string]
        freq, idx = vocab.count, vocab.index
        if freq < min_count:
            continue
        vector = w2v_model.wv.vectors[idx]
        vector_map.borrow(string, freq, vector)

    print("saving the model to file...")
    vector_map.save(out_path)
```

**Comment by ines** [comment]
@tolomaus Thanks for sharing your code!

Sorry I haven't had time to update the scripts yet. I just uploaded the updated preprocessing script that takes a text file and converts it to the sense2vec format. See [`bin/preprocess.py`](https://github.com/explosion/sense2vec/blob/master/bin/preprocess.py).

Example input:
```
Rats, mould and broken furniture: the scandal of the UK's refugee housing
```

Example output:
```
Rats|NOUN ,|PUNCT mould|NOUN and|CCONJ broken_furniture|NOUN :|PUNCT the|DET scandal|NOUN of|ADP the|DET UK|GPE 's|PART refugee_housing|NOUN
```

**Comment by jehrodrigues** [comment]
@tolomaus, what version of gensim are you using? I am having the following error in this line:

vector = w2v_model.wv.vectors [idx]

AttributeError: 'KeyedVectors' object has no attribute 'vectors'

**Comment by tolomaus** [comment]
I'm using the latest version of gensim: 3.4.0

**Comment by poojasakhalkar** [comment]
@ines bin/preprocess.py gives me an error,
ImportError: cannot import name 'transform_doc'

**Comment by lohithpro** [comment]
Still waiting

**Comment by HiranD** [comment]
> 
> 
> Indeed, building a custom sense2vec model is not all that complicated, see here a summary of how to do it, based on the scripts found in the previous version:
> 
> ```
>     w2v_model = Word2Vec(
>         size=size,
>         window=window,
>         min_count=min_count,
>         workers=workers,
>         sample=1e-5,
>         negative=negative,
>         iter=epochs
>     )
> 
>     sentences = PathLineSentences(path)
> 
>     print("building the vocabulary...")
>     w2v_model.build_vocab(sentences)
> 
>     print("training the model...")
>     w2v_model.train(sentences, total_examples=w2v_model.corpus_count, epochs=w2v_model.iter)
> 
>     print("creating the sense2vec model...")
>     vector_map = VectorMap(size)
> 
>     for string in w2v_model.wv.vocab:
>         vocab = w2v_model.wv.vocab[string]
>         freq, idx = vocab.count, vocab.index
>         if freq < min_count:
>             continue
>         vector = w2v_model.wv.vectors[idx]
>         vector_map.borrow(string, freq, vector)
> 
>     print("saving the model to file...")
>     vector_map.save(out_path)
> ```

Please do consider about dimensions (`size=size`) of word2vec model. Otherwise you will get an error for `sense2vec.load(vectors_path)`. Because in `__init__.py` `load(vectors_path)` method has a `vector_map = VectorMap(128)` line that configured to `size=128`. If you want to change the dimension to something else, change the whole thing.

**Comment by SamPortnow** [comment]
I'm having some trouble in training my own vectors. I used the scripts posted above in the bin folder. The preprocess step worked fine, but I'm getting an error in the train step. 

Here is the the call I make to the train function:

train(in_dir = '/home/portnows/preprocessed', out_file = '/home/portnows/trained')


Traceback (most recent call last):
  File "/home/portnows/tmp/Rtmp5o4CVd/chunk-code-bf0842242e06.txt", line 41, in <module>
    train(in_dir = '/home/portnows/preprocessed', out_file = '/home/portnows/trained')
  File "/home/portnows/tmp/Rtmp5o4CVd/chunk-code-bf0842242e06.txt", line 37, in train
    vector_map.save(out_file)
  File "vectors.pyx", line 195, in sense2vec.vectors.VectorMap.save
TypeError: write_json() missing 1 required positional argument: 'data'

Any ideas what might be causing this? The documentation makes it seem that out_file should be a directory where json gets stored, but should it actually be a file?

**Comment by ines** [comment]
Sorry for the confusion around this! As part of the refactor (see #77), I've updated the scripts and added more info and checks. The preprocessing script takes a text file as input and a text file as output. The training script takes a text file or a directory of text files as input, and a directory path as output (will be created if it doesn't exist). The output is a model component directory that can be loaded via `Sense2Vec.from_disk`.

New scripts: https://github.com/explosion/sense2vec/tree/refactor/scripts
New README: https://github.com/explosion/sense2vec/blob/refactor/README.md

**Comment by jaytimbadia** [comment]
> Sorry for the confusion around this! As part of the refactor (see #77), I've updated the scripts and added more info and checks. The preprocessing script takes a text file as input and a text file as output. The training script takes a text file or a directory of text files as input, and a directory path as output (will be created if it doesn't exist). The output is a model component directory that can be loaded via `Sense2Vec.from_disk`.
> 
> New scripts: https://github.com/explosion/sense2vec/tree/refactor/scripts
> New README: https://github.com/explosion/sense2vec/blob/refactor/README.md

Hi @ines ,

Hope you all are safe.

I need to train sense2vec since I am working on a different domain.
I just wanna know, how long it takes to train a model, lets say I have a data 10 MB text file of (harry potter all series).
Also is CPU enough to train?

I need time since time is very key in our case since data needs to be delivered with minutes as tolerance.

Thanks in Advance!!

**Comment by avishalom** [comment]
links are broken

**Comment by henokDES** [comment]
@ines i am having this error : AttributeError: 'spacy.vectors.Vectors' object has no attribute 'borrow'

please help me out
