### ISSUE TITLE
Some errors come up when I install the sense2vec.

### ISSUE THREAD

**Issue by artemisrj** [explosion/sense2vec#4]
I install the spacy package and download the sense2vec project.When I unzip the sense2vec-master.zip and run the 'python setup.py install' to install the sense2vec,there are some errors.

`cadevil@cadevil:~/zrj/sense2vec-master$ python setup.py install
Cythonizing sources
sense2vec/vectors.pyx has not changed
running install
running bdist_egg
running egg_info
writing requirements to sense2vec.egg-info/requires.txt
writing sense2vec.egg-info/PKG-INFO
writing top-level names to sense2vec.egg-info/top_level.txt
writing dependency_links to sense2vec.egg-info/dependency_links.txt
reading manifest file 'sense2vec.egg-info/SOURCES.txt'
writing manifest file 'sense2vec.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'sense2vec.vectors' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/cadevil/anaconda/include/python2.7 -I/home/cadevil/zrj/sense2vec-master/include -I/home/cadevil/anaconda/include/python2.7 -c sense2vec/vectors.cpp -o build/temp.linux-x86_64-2.7/sense2vec/vectors.o -O3 -Wno-unused-function -fopenmp -fno-stack-protector
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/cadevil/zrj/sense2vec-master/include/numpy/ndarraytypes.h:1804:0,
                 from /home/cadevil/zrj/sense2vec-master/include/numpy/ndarrayobject.h:17,
                 from /home/cadevil/zrj/sense2vec-master/include/numpy/arrayobject.h:4,
                 from sense2vec/vectors.cpp:267:
/home/cadevil/zrj/sense2vec-master/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
sense2vec/vectors.cpp: In function ‘PyObject\* __pyx_pf_9sense2vec_7vectors_11VectorStore_12load(__pyx_obj_9sense2vec_7vectors_VectorStore_, PyObject_)’:
sense2vec/vectors.cpp:6769:11: error: cannot declare pointer to ‘float&’
   float &___pyx_v_ptr;
           ^
sense2vec/vectors.cpp: In function ‘void __pyx_f_9sense2vec_7vectors_linear_similarity(int_, float_, float_, int, const float_, int, const float_ const_, const float_, int, __pyx_t_9sense2vec_7vectors_do_similarity_t)’:
sense2vec/vectors.cpp:7323:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_4 = ((__pyx_v_queue.size() > __pyx_v_nr_out) != 0);
                                          ^
error: command 'gcc' failed with exit status 1

`
I update the cython to the newest version and the problem didn't be solved.The system is Unbuntu and the python version is 2.7

**Comment by henningpeters** [comment]
I have seen this error before on my system. It disappeared after reinstantiating virtualenv and/or running ```python setup.py clean```. Can you please try those?

Also, I recommend you to install via ```pip install -e .``` or ```pip install -e git+git://github.com/spacy-io/sense2vec.git#egg=sense2vec```.

**Comment by solipsy** [comment]
Hi,

I have the exact same issue on Linux Mint 17.3. Here's the terminal output after issuing `pip install -e git+git://github.com/spacy-io/sense2vec.git#egg=sense2vec`:

`building 'sense2vec.vectors' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -I/home/solipsy/src/sense2vec/include -I/usr/include/python2.7 -c sense2vec/vectors.cpp -o build/temp.linux-x86_64-2.7/sense2vec/vectors.o -O3 -Wno-unused-function -fno-stack-protector
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1761:0,
                     from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                     from /usr/include/python2.7/numpy/arrayobject.h:4,
                     from sense2vec/vectors.cpp:362:
    /usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    sense2vec/vectors.cpp: In function ‘PyObject* __pyx_pf_9sense2vec_7vectors_11VectorStore_12load(__pyx_obj_9sense2vec_7vectors_VectorStore*, PyObject*)’:
    sense2vec/vectors.cpp:6352:11: error: cannot declare pointer to ‘float&’
       float &*__pyx_v_ptr;
               ^
    sense2vec/vectors.cpp: In function ‘void __pyx_f_9sense2vec_7vectors_linear_similarity(int*, float*, float*, int, const float*, int, const float* const*, const float*, int, __pyx_t_9sense2vec_7vectors_do_similarity_t)’:
    sense2vec/vectors.cpp:6871:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           __pyx_t_4 = ((__pyx_v_queue.size() > __pyx_v_nr_out) != 0);
                                                ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/solipsy/src/sense2vec/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/solipsy/src/sense2vec/
`

I also ran `python setup.py clean`, but I don't use virtualenv. I'd be grateful for any suggestion.

Thanks!

**Comment by henningpeters** [comment]
Thanks, working on a replacement of that code.
