### ISSUE TITLE
Argument Key has the incorrect type

### ISSUE THREAD

**Issue by lmp94** [explosion/sense2vec#40]
When working through in my python terminal when I enter 
freq, query_vector = model["natural_language_processing|NOUN"] 
I get this error. I am just trying to simply use the basic model. 

![screen shot 2017-11-12 at 3 26 55 pm](https://user-images.githubusercontent.com/8905439/32705502-2ad069f2-c7e3-11e7-8f0a-eb4a5ec99983.png)
![screen shot 2017-11-12 at 3 25 58 pm](https://user-images.githubusercontent.com/8905439/32705503-2add1134-c7e3-11e7-81a8-c421a3381d79.png)

**Comment by jakebian** [comment]
- Just replace the key with `u"natural_etc..."`
- or import `unicode_literals`, [looks like this is already a PR](https://github.com/explosion/sense2vec/pull/33)
