### ISSUE TITLE
Error when trying to open Reddit Vectors downloaded

### ISSUE THREAD

**Issue by jediwarpraptor** [explosion/sense2vec#44]
![image](https://user-images.githubusercontent.com/17027856/38497329-c186e2ea-3bce-11e8-9c13-5bd43a3bb98e.png)

The code right now is super-simple:

```
from sense2vec import Sense2VecComponent
import spacy

nlp = spacy.load('en_core_web_sm')
s2v = Sense2VecComponent('./reddit-vectors-1.1.0')
nlp.add_pipe(s2v)

```
Fails with "Could not open binary file" - the file is definitely there.  Installed into its own venv with this `sense2vec` dev branch + `spacy` + newly downloaded `en_core_web_sm`.

**Comment by ines** [comment]
Thanks for the report. One thing that's definitely missing in the `load` method is validation of the path. Right now, "Could not open binary file" can mean lots of things – file not found, full path incorrect, file corrupted etc., which makes it tricky to debug. Will put this on my list of enhancements for the stable v1.0!

As a quick sanity check, could you try using the absolute path to the vectors directory and/or checking that `os.path.exists(your_path_here)` returns `True` at the top of your file?

**Comment by jediwarpraptor** [comment]
Uggh... feel free to tag this issue as "Resolved-Delusional" (I used to like to keep that status handy for situations like this).

For future reference, it turns out that - apparently - `./reddit-vectors-1.1.0`  is not the same thing as `./reddit_vectors-1.1.0`.  Who knew?

**Comment by ines** [comment]
Thanks for updating! And don't worry – I mean, I didn't spot this either 😉
