### ISSUE TITLE
Potential Issues with the same Term being tagged with two "senses"

### ISSUE THREAD

**Issue by jediwarpraptor** [explosion/sense2vec#45]
I was doing some casual testing of similarity and found something that seems to be a bug or at least an inconsistency that could be problematic for people.

It looks like the Entity tagging for the original training set behaves slightly differently than the tagging used for on-the-fly similarity comparisons.  The issue is primarily focused around names of people.  So, for at least a few different people ("Quentin Tarantino", "Dan Harmon", etc) they appear within the `vectors` table tagged as a `PERSON`.  However, when parsing documents on the fly with the model and then looking for similarity, the keys aren't found.  This is because they are being compared using a differently calculated "sense".  They both show up within the target doc tagged as `PROPN`.

So, here you see that `Dan_Harmon|PERSON` is returned as semantically related to the phrase "writers_room" - which is perfectly legit and makes a ton of sense. 

![image](https://user-images.githubusercontent.com/17027856/38511773-37e9cbb4-3bf7-11e8-81cb-bde895458f25.png)

 However, if I try to parse the sentence:  "Dan Harmon is one of my favorite writers" or "I really like Dan Harmon as a writer", it yields a Key Error with ...

![image](https://user-images.githubusercontent.com/17027856/38511797-4ce588b4-3bf7-11e8-96a5-bf8fdd36109b.png)

There are probably a few ways to change this around (maybe by pre-emptively changing out `PROPN` tokens to `PERSON` ? - but that feels like it will almost certainly backfire).  

Let me know your thoughts.

**Comment by ines** [comment]
The thing in this case is that sense2vec supports both part-of-speech tags *and* entity labels. `PROPN` is the POS tag, whereas `PERSON` is the entity label. And spaCy has no way of knowing which one to pick.

To solve this, I tried the current solution, which adds custom attributes to both tokens and spans. By default, the spaCy pipeline component uses the part-of-speech tag for tokens and the entity label for spans. Entities (accessed via `doc.ents`) are always spans – so you can do the following if you want to look up entities:

```python
for ent in doc.ents:
   if ent._.in_s2v:
       most_similar = ent._.s2v_most_similar(5)
```

**Comment by jediwarpraptor** [comment]
In my case, I may try to modify it to fall back to check entities if it gets a KeyError on the POS.  Either way, it makes sense now.  Still learning the spaCy model/architecture.  Thanks!
