### ISSUE TITLE
sense2vec and spacy

### ISSUE THREAD

**Issue by ivy-jiang** [explosion/sense2vec#46]
I get an error when I try to import sense2vec after I import spacy (v2.0.11):

    import sense2vec
  File "/usr/local/lib/python3.5/dist-packages/sense2vec/__init__.py", line 2, in <module>
    from .vectors import VectorMap
  File ".env/lib/python2.7/site-packages/spacy/strings.pxd", line 18, in init sense2vec.vectors (sense2vec/vectors.cpp:26598)
ValueError: spacy.strings.StringStore has the wrong size, try recompiling

I am using python3- is that the issue?

**Comment by ivy-jiang** [comment]
Okay- I just ran:
sudo pip3 install sense2vec==1.0.0a0

and this resolved it. Thanks!

**Comment by ines** [comment]
Thanks for updating with your solution! If you just ran `pip install sense2vec`, you probably accidentally got the old version instead of the spaCy v2.x-compatible release (which is only an alpha version at the moment).
