### ISSUE TITLE
Sense2vec and Spacy: How to choose the "sense" i.e. POS or entity labels 

### ISSUE THREAD

**Issue by ivy-jiang** [explosion/sense2vec#48]
Using Sense2vec in conjunction with Spacy, is there a way to choose the part-of speech tag/ entity label for a token when the attribute s2v_most_similar is applied?

e.g. for the token "duck", the default sense/POS is NOUN when the attribute s2v_most_similar is applied. 
Using spacy with sense2vec, is there a way to get the s2v_most_similar for "duck" as in the VERB?

Thanks!

**Comment by ines** [comment]
By default, the spaCy extension uses the POS tag assigned to the token – so if your spaCy model predicted `NOUN`, it will look up this sense. To use entity labels, you can check the respective attributes on the entrie in `doc.ents` instead.

If you want more control over the senses and apply them manually, you might prefer the [standalone `sense2vec` usage](https://github.com/explosion/sense2vec#standalone-usage). The pipeline component is really just [a wrapper around the library](https://github.com/explosion/sense2vec/blob/702d9a1e10916e656b6c0cd938fc4ffe12eaeb59/sense2vec/__init__.py#L18).
