### ISSUE TITLE
Error when loading reddit_vectors-1.1.0

### ISSUE THREAD

**Issue by GregSilverman** [explosion/sense2vec#49]
Adding to existing Jupyter notebook that is run from a docker container, I do the following:

`import sense2vec`
`s2v = sense2vec.load('reddit_vectors-1.1.0')`

which throws the error:

```
/usr/local/lib/python3.5/dist-packages/sense2vec/util.py in get_package_by_name(name, via)
     18                                name or about.default_model, data_path=via)
     19     except PackageNotFoundException as e:
---> 20         raise RuntimeError("Model not installed. Please run 'python -m "
     21                            "sense2vec.download' to install latest compatible "
     22                            "model.")

Model not installed. Please run 'python -m sense2vec.download' to install latest compatible model.
```

I then create a local image of the container using a TensorFlow Dockerfile, and  in the Dockerfile I issue `RUN pip install sense2vec` when building my Docker container, but if I do a `RUN ipython -m sense2vec.download` I get an error that  `print("Model already installed. Please run '%s --force to reinstall." % sys.argv[0], file=sys.stderr)`
`AttributeError: module 'sense2vec.about' has no attribute '__title__'`. 

The same happens if I SSH into the Docker container, that is, if I do an `ipython -m sense2vec.download` from the command line I get the error that `print("Model already installed. Please run '%s --force to reinstall." % sys.argv[0], file=sys.stderr)` 

The iPython version is 3.5.  Docker container's OS version is 64-bit: ` SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

I just noticed the requirement of CPython. Since Jupyter uses iPython, I suppose there is no way to get this to work? even if so, why the discrepancy is error from outside the container and inside it?

Please advise.

**Comment by ines** [comment]
It looks like you might be running `v0.x` instead of `v1.0.0a0` (i.e. the latest alpha version). Sorry, this isn't very clear in the `README` – I might add an explicit note. To install the alpha, you have to tell pip the version number explicitly:

```bash
pip install sense2vec==1.0.0a0
```

> I just noticed the requirement of CPython. Since Jupyter uses iPython, I suppose there is no way to get this to work?

That should be no problem – under the hood, you're most likely running CPython, which then powers your iPython environment.

**Comment by GregSilverman** [comment]
Got it. Now, I am getting an error when installing the alpha version:

 ```
Downloading https://files.pythonhosted.org/packages/28/4a/a1d9a28545adc839789c1442e7314cb0c70b8657a885f9e5b287fade7814/sense2vec-1.0.0a0.tar.gz (311kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vln916it/sense2vec/setup.py", line 169, in <module>
        setup_package()
      File "/tmp/pip-build-vln916it/sense2vec/setup.py", line 107, in setup_package
        readme = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5413: ordinal not in range(128)
```

Appreciate the help!

**Comment by GregSilverman** [comment]
I've tried everything here, to no avail: [pip-install-numpy-throws-an-error-ascii-codec-cant-decode-byte-0xe2](https://stackoverflow.com/questions/26473681/pip-install-numpy-throws-an-error-ascii-codec-cant-decode-byte-0xe2)

**Comment by GregSilverman** [comment]
Unable to get this working in my Docker container (using the Dockerfile here:https://github.com/adeshpande3/LSTM-Sentiment-Analysis). Will try using it locally with SpaCy at some point.

**Comment by GregSilverman** [comment]
As soon as I posted this, I tried downgrading my version of Python, and lo' and behold, it worked! Not sure why, since on my laptop I am running Anaconda version 3.6.5. Anyway, all is well!

**Comment by GregSilverman** [comment]
I now figured out what was going on. I needed to install python 2.7 for a specific app, and thus, the original version of pip was pointing to the 3.5 version of python. Using the correct version of pip resolved this.
