### ISSUE TITLE
I'm not able to use the '.add_pipe' attribute

### ISSUE THREAD

**Issue by MotorCityCobra** [explosion/sense2vec#51]
>>> nlp.add_pipe(s2v)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'English' object has no attribute 'add_pipe'

Is it called something else now?

**Comment by ines** [comment]
Looks like you might be using an older version of spaCy – the new [custom pipeline components](https://spacy.io/usage/processing-pipelines#custom-components) all require `v2.x`. (You can check your spaCy version by running `python -m spacy info` on the command line.) 

If you need to upgrade from `v1.x` to `v2.x`, see [this guide](https://spacy.io/usage/v2#migrating) for more details. I'd also recommend using a fresh (virtual) environment for the new installation!

**Comment by MotorCityCobra** [comment]
That 'python -m space info' command didn't work.  

I found this solution.

    $ python
    >>> import pkg_resources
    >>> pkg_resources.get_distribution("spacy").version
    '0.101.0'  

Thanks for the diagnosis. I've follow your link and get the newer version.  
I'll assume that will fix it and close the issue.
