### ISSUE TITLE
On installation: UnicodeDecodeError.

### ISSUE THREAD

**Issue by GerhardDeuter** [explosion/sense2vec#52]
I tried to install sense2vec from python 3.6.5, 64bit and encountered the following encoding error:

py -3 -m pip install sense2vec==1.0.0a0
Collecting sense2vec==1.0.0a0
  Using cached https://files.pythonhosted.org/packages/28/4a/a1d9a28545adc839789c1442e7314cb0c70b8657a885f9e5b287fade7814/sense2vec-1.0.0a0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MyUser\AppData\Local\Temp\pip-install-21y0wglc\sense2vec\setup.py", line 169, in <module>
        setup_package()
      File "C:\Users\MyUser\AppData\Local\Temp\pip-install-21y0wglc\sense2vec\setup.py", line 107, in setup_package
        readme = f.read()
      File "C:\Program Files\Python64\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 13089: character maps to <undefined>

Any quick ideas on how to fix that?

**Comment by GerhardDeuter** [comment]
Making the following changes in the setup.py worked for me. Installed the package manually from the extracted (and modified) directory: py -3 -m pip install .

`with open(os.path.join(root, src_path, 'about.py'), encoding="utf8") as f:
            about = {}
            exec(f.read(), about)

        with open(os.path.join(root, 'README.rst'), encoding="utf8") as f:
            readme = f.read()`

**Comment by tolomaus** [comment]
I had a similar issue on ubuntu 18.04:

```
root@521b165b15f4:/usr/src/app# pip3 install sense2vec==1.0.0.0a0
Collecting sense2vec==1.0.0.0a0
  Downloading https://files.pythonhosted.org/packages/28/4a/a1d9a28545adc839789c1442e7314cb0c70b8657a885f9e5b287fade7814/sense2vec-1.0.0a0.tar.gz (311kB)
    100% |################################| 317kB 5.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-81gs70om/sense2vec/setup.py", line 169, in <module>
        setup_package()
      File "/tmp/pip-install-81gs70om/sense2vec/setup.py", line 107, in setup_package
        readme = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5413: ordinal not in range(128)
```

Installing from source (without modification) worked fine:

```
cd /usr/src && \
git clone https://github.com/explosion/sense2vec && \
cd sense2vec && \
python3 setup.py config && \
pip3 install .
```

**Comment by frozamilan1899** [comment]
@GerhardDeuter Thank you. Your approach succeeded in solving the problems that plagued me.

**Comment by DarianHarrison** [comment]
this solved for me, 

I had to reset the encoding of my system by the below command;

export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_TYPE=en_US.UTF-8
