### ISSUE TITLE
sense2vec version that supports python3.7

### ISSUE THREAD

**Issue by galrapo** [explosion/sense2vec#64]
Hi, 

As the current most updated version of python is V3.7, I'm wondering whether there's a sense2vec library version that support that version.

**Comment by frozamilan1899** [comment]
It seems that there is no library for this version, because I have tried several approaches but still failed

**Comment by ines** [comment]
The latest version should be compatible with the latest spaCy and also support 3.7. The upcoming version (see #77) will also supoort 3.8.
