### ISSUE TITLE
Cymen compatibility of sense2vec and spacy are not the same

### ISSUE THREAD

**Issue by cyrilou242** [explosion/sense2vec#65]
Hello,

The cymem requirements for last sense2vec is  cymem>=1.30,<1.32
The cymem requirements for last spacy is cymem>=2.0.2,<2.1.0

I know pip doesn't manage backwards dependency, so I tried to install spacy and sense2vec in the 2 different orders.
This was tried on python 3.5.6

When I install sense2vec first and spacy after:   
`pip install sense2vec==1.0.0a0`
(import and loading of reddit vectors is working)
`pip install -U spacy`
`python -m spacy download en`

Then when I try to run the hello world:  
`import spacy`
`from sense2vec import Sense2VecComponent`
`nlp = spacy.load('en')`
`s2v = Sense2VecComponent('/path/to/reddit_vectors-1.1.0')`

I got the following error: 

> Traceback (most recent call last):
>   File "/Users/cyril/PycharmProjects/CTA_sense2vec/test.py", line 2, in <module> . 
>     from sense2vec import Sense2VecComponent . 
>   File "/Users/cyril/PycharmProjects/CTA_sense2vec/venv/lib/python3.5/site-packages/sense2vec/__init__.py", line 4, in <module>
>     from .vectors import VectorMap
>   File "cymem.pxd", line 1, in init sense2vec.vectors
> ValueError: cymem.cymem.Pool has the wrong size, try recompiling. Expected 64, got 48

When I install spacy first and sense2vec after (in a new virtual env): 
I got the following error:

> Traceback (most recent call last):
>   File "/Users/cyril/PycharmProjects/CTA_sense2vec_2/test.py", line 1, in <module>
>     import spacy
>   File "/Users/cyril/PycharmProjects/CTA_sense2vec_2/venv/lib/python3.5/site-packages/spacy/__init__.py", line 8, in <module>
>     from thinc.neural.util import prefer_gpu, require_gpu
>   File "/Users/cyril/PycharmProjects/CTA_sense2vec_2/venv/lib/python3.5/site-packages/thinc/neural/__init__.py", line 1, in <module>
>     from ._classes.model import Model
>   File "/Users/cyril/PycharmProjects/CTA_sense2vec_2/venv/lib/python3.5/site-packages/thinc/neural/_classes/model.py", line 12, in <module>
>     from ..train import Trainer
>   File "/Users/cyril/PycharmProjects/CTA_sense2vec_2/venv/lib/python3.5/site-packages/thinc/neural/train.py", line 3, in <module>
>     from .optimizers import Adam, SGD, linear_decay
>   File "optimizers.pyx", line 13, in init thinc.neural.optimizers
>   File "cymem.pxd", line 4, in init thinc.neural.ops
> AttributeError: module 'cymem.cymem' has no attribute 'PyMalloc'

  

It really seems for me that in any case I am breaking the cymem dependency of one of the library. 
Did I miss something ?

**Comment by julien-c** [comment]
@cyrilou242 @calebdel The requirement upgrade for `cymem` in spaCy is [rather recent](https://github.com/explosion/spaCy/commit/6e6f6be3f5714ccdec80f8611147b02c6b102432#diff-b4ef698db8ca845e5845c4618278f29a) (last october), so you could try installing a slightly older version of spaCy.

cc @ines

**Comment by julien-c** [comment]
Changed this slightly to:
```
spacy==v2.0.12
sense2vec==1.0.0a0
msgpack==0.5.6
```

**Comment by CarrollAetna** [comment]
Hey I know this was closed, but wanted to point out this fix appears to be problematic for a native install on Mac running Mojave 10.14. 

Spacy 2.0.12 appears to have issues on Macs not sure if it extends to other Mac OS versions. 

https://github.com/huggingface/neuralcoref/issues/105

My current workaround is just using a docker container as my dev machine.
