### ISSUE TITLE
install sense2vec on mojave

### ISSUE THREAD

**Issue by junyanp** [explosion/sense2vec#66]
Collecting sense2vec==1.0.0a0
  Using cached https://files.pythonhosted.org/packages/28/4a/a1d9a28545adc839789c1442e7314cb0c70b8657a885f9e5b287fade7814/sense2vec-1.0.0a0.tar.gz
Requirement already satisfied: numpy>=1.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sense2vec==1.0.0a0) (1.15.0)
Requirement already satisfied: ujson>=1.35 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sense2vec==1.0.0a0) (1.35)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sense2vec==1.0.0a0) (1.0.1)
Requirement already satisfied: murmurhash<0.29,>=0.28 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sense2vec==1.0.0a0) (0.28.0)
Requirement already satisfied: cymem<1.32,>=1.30 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sense2vec==1.0.0a0) (1.31.2)
Installing collected packages: sense2vec
  Running setup.py install for sense2vec ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/fl/16v92h311z55cljkhrhlh30m0000gn/T/pip-install-k2nj2n_g/sense2vec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/fl/16v92h311z55cljkhrhlh30m0000gn/T/pip-record-7ia78okh/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/sense2vec
    copying sense2vec/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/sense2vec
    copying sense2vec/about.py -> build/lib.macosx-10.9-x86_64-3.7/sense2vec
    copying sense2vec/spacy_pipeline.py -> build/lib.macosx-10.9-x86_64-3.7/sense2vec
    creating build/lib.macosx-10.9-x86_64-3.7/sense2vec/tests
    copying sense2vec/tests/conftest.py -> build/lib.macosx-10.9-x86_64-3.7/sense2vec/tests
    copying sense2vec/tests/test_vectors.py -> build/lib.macosx-10.9-x86_64-3.7/sense2vec/tests
    copying sense2vec/tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/sense2vec/tests
    copying sense2vec/tests/test_sense2vec.py -> build/lib.macosx-10.9-x86_64-3.7/sense2vec/tests
    copying sense2vec/_strings.pyx -> build/lib.macosx-10.9-x86_64-3.7/sense2vec
    copying sense2vec/vectors.pyx -> build/lib.macosx-10.9-x86_64-3.7/sense2vec
    copying sense2vec/cfile.pyx -> build/lib.macosx-10.9-x86_64-3.7/sense2vec
    copying sense2vec/cfile.pxd -> build/lib.macosx-10.9-x86_64-3.7/sense2vec
    copying sense2vec/vectors.pxd -> build/lib.macosx-10.9-x86_64-3.7/sense2vec
    copying sense2vec/__init__.pxd -> build/lib.macosx-10.9-x86_64-3.7/sense2vec
    copying sense2vec/_strings.pxd -> build/lib.macosx-10.9-x86_64-3.7/sense2vec
    running build_ext
    building 'sense2vec.vectors' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/sense2vec
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/private/var/folders/fl/16v92h311z55cljkhrhlh30m0000gn/T/pip-install-k2nj2n_g/sense2vec/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c sense2vec/vectors.cpp -o build/temp.macosx-10.9-x86_64-3.7/sense2vec/vectors.o -O3 -Wno-unused-function -fno-stack-protector
    In file included from sense2vec/vectors.cpp:508:
    In file included from /private/var/folders/fl/16v92h311z55cljkhrhlh30m0000gn/T/pip-install-k2nj2n_g/sense2vec/include/numpy/arrayobject.h:15:
    In file included from /private/var/folders/fl/16v92h311z55cljkhrhlh30m0000gn/T/pip-install-k2nj2n_g/sense2vec/include/numpy/ndarrayobject.h:17:
    In file included from /private/var/folders/fl/16v92h311z55cljkhrhlh30m0000gn/T/pip-install-k2nj2n_g/sense2vec/include/numpy/ndarraytypes.h:1728:
    /private/var/folders/fl/16v92h311z55cljkhrhlh30m0000gn/T/pip-install-k2nj2n_g/sense2vec/include/numpy/npy_deprecated_api.h:11:2: warning: "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
     ^
    sense2vec/vectors.cpp:9861:42: warning: comparison of integers of different signs: 'std::__1::priority_queue<std::__1::pair<float, int>, std::__1::vector<std::__1::pair<float, int>, std::__1::allocator<std::__1::pair<float, int> > >, std::__1::less<std::__1::pair<float, int> > >::size_type' (aka 'unsigned long') and 'int' [-Wsign-compare]
          __pyx_t_4 = ((__pyx_v_queue.size() > __pyx_v_nr_out) != 0);
                        ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~
    sense2vec/vectors.cpp:9723:21: warning: code will never be executed [-Wunreachable-code]
            if (1 == 0) abort();
                        ^~~~~
    sense2vec/vectors.cpp:9723:13: note: silence by adding parentheses to mark code as explicitly dead
            if (1 == 0) abort();
                ^
                /* DISABLES CODE */ ( )
    sense2vec/vectors.cpp:31777:24: error: no member named 'exc_type' in '_ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    sense2vec/vectors.cpp:31778:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    sense2vec/vectors.cpp:31779:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    sense2vec/vectors.cpp:31780:13: error: no member named 'exc_type' in '_ts'
        tstate->exc_type = *type;
        ~~~~~~  ^
    sense2vec/vectors.cpp:31781:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tstate->exc_value = *value;
                ^~~~~~~~~
                curexc_value
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    sense2vec/vectors.cpp:31782:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = *tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    sense2vec/vectors.cpp:32757:21: error: no member named 'exc_type' in '_ts'
        *type = tstate->exc_type;
                ~~~~~~  ^
    sense2vec/vectors.cpp:32758:22: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        *value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    sense2vec/vectors.cpp:32759:19: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        *tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    sense2vec/vectors.cpp:32766:24: error: no member named 'exc_type' in '_ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    sense2vec/vectors.cpp:32767:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    sense2vec/vectors.cpp:32768:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    sense2vec/vectors.cpp:32769:13: error: no member named 'exc_type' in '_ts'
        tstate->exc_type = type;
        ~~~~~~  ^
    sense2vec/vectors.cpp:32770:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tstate->exc_value = value;
                ^~~~~~~~~
                curexc_value
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    sense2vec/vectors.cpp:32771:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    sense2vec/vectors.cpp:32816:24: error: no member named 'exc_type' in '_ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    sense2vec/vectors.cpp:32817:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    sense2vec/vectors.cpp:32818:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    sense2vec/vectors.cpp:32819:13: error: no member named 'exc_type' in '_ts'
        tstate->exc_type = local_type;
        ~~~~~~  ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    3 warnings and 20 errors generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/fl/16v92h311z55cljkhrhlh30m0000gn/T/pip-install-k2nj2n_g/sense2vec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/fl/16v92h311z55cljkhrhlh30m0000gn/T/pip-record-7ia78okh/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/fl/16v92h311z55cljkhrhlh30m0000gn/T/pip-install-k2nj2n_g/sense2vec/

**Comment by nateraw** [comment]
Same issue here.

**Comment by xandroxygen** [comment]
I also have the same issue, even with a fresh install.

**Comment by nateraw** [comment]
The issue is that some underlying C libraries have change on Mojave. :persevere:

**Comment by aydemirfb** [comment]
Same issue

**Comment by hmswaffles** [comment]
Same issue.

**Comment by quillan86** [comment]
Same issue.

**Comment by GaspardDebussche** [comment]
Same issue.

**Comment by ines** [comment]
See #67 for the solution. 

The upcoming stable version (see #77) was completely refactored from scratch and is now a pure Python module. This should hopefully make installation much simpler in the future 🙂
