### ISSUE TITLE
ImportError: cannot import name 'transform_doc'  /bin/preprocess.py 

### ISSUE THREAD

**Issue by isarth** [explosion/sense2vec#69]

**Comment by HiranD** [comment]
install sense2vec using setup.py after cloning the git. This error comes when you try to use pip install.

**Comment by ines** [comment]
This sounds like you've ended up with the wrong version installed. The files on `master` refer to the latest alpha, so you need to tell `pip` to install that explicitly: `pip install sense2vec==1.0.0a1`.
