### ISSUE TITLE
ModuleNotFoundError: No module named 'sense2vec'

### ISSUE THREAD

**Issue by Jbsalinas78** [explosion/sense2vec#71]
I have installed sense2vec in Windows 10 using the latest versions. Results of the validate command are found below:

 C:\WINDOWS\system32>python -m spacy validate
✔ Loaded compatibility table

====================== Installed models (spaCy v2.1.4) ======================
ℹ spaCy installation:
C:\xyz\xyz\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy

TYPE      NAME                MODEL               VERSION
package   en-vectors-web-lg   en_vectors_web_lg   2.1.0     ✔
package   en-core-web-sm      en_core_web_sm      2.1.0     ✔
package   en-core-web-lg      en_core_web_lg      2.1.0     ✔

When I try to import sense2vec using:
import spacy
from sense2vec import Sense2VecComponent
I get:
ModuleNotFoundError: No module named 'sense2vec'

any insight is appreciated. Thanks in advance.

**Comment by baerbock** [comment]
Please don't use Windows.
